//! Witnesses for the typed Cargo.lock model: winnow pin grammar and
//! format-preserving repin.

use synchronizer::cargo_lock::CargoLock;
use synchronizer::cargo_manifest::{DependencyName, GitReference, PackageVersion};
use synchronizer::error::{Error, UnbumpablePinReason};
use synchronizer::types::{BranchName, CommitIdentifier, ComponentName};

const LOCK_TEXT: &str = r#"# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "serde"
version = "1.0.228"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "9a8e94ea7f378bd32cbbd37198a4a91436180c5bb472411e48b5ec2e2124ae9e"

[[package]]
name = "signal-frame"
version = "0.2.0"
source = "git+https://github.com/LiGoldragon/signal-frame.git?branch=main#1111111111111111111111111111111111111111"

[[package]]
name = "signal-router"
version = "0.1.0"
dependencies = [
 "serde",
 "signal-frame",
]
"#;

#[test]
fn git_pins_parse_through_the_winnow_grammar() {
    let component = ComponentName::new("signal-router");
    let lock = CargoLock::from_toml_text(LOCK_TEXT, &component).expect("lock decodes");
    let packages = lock.git_packages().expect("git pins parse");
    assert_eq!(packages.len(), 1, "registry sources produce no pin");
    let (name, pin) = &packages[0];
    assert_eq!(name.as_str(), "signal-frame");
    assert_eq!(
        pin.url().as_str(),
        "https://github.com/LiGoldragon/signal-frame.git"
    );
    assert_eq!(pin.reference(), &GitReference::Branch(BranchName::main()));
    assert_eq!(
        pin.revision().as_str(),
        "1111111111111111111111111111111111111111"
    );
}

#[test]
fn repin_changes_exactly_the_pinned_entry_and_preserves_the_rest() {
    let component = ComponentName::new("signal-router");
    let mut lock = CargoLock::from_toml_text(LOCK_TEXT, &component).expect("lock decodes");
    let next = CommitIdentifier::new("2222222222222222222222222222222222222222");
    let previous = lock
        .repin_git_package(
            &DependencyName::new("signal-frame"),
            GitReference::Branch(BranchName::synchronizer()),
            next,
            Some(PackageVersion::new("0.3.0")),
        )
        .expect("locked git package repins");
    assert_eq!(
        previous.as_str(),
        "1111111111111111111111111111111111111111"
    );
    let rendered = lock.to_toml_text();
    let expected = LOCK_TEXT
        .replace(
            "version = \"0.2.0\"",
            "version = \"0.3.0\"",
        )
        .replace(
            "source = \"git+https://github.com/LiGoldragon/signal-frame.git?branch=main#1111111111111111111111111111111111111111\"",
            "source = \"git+https://github.com/LiGoldragon/signal-frame.git?branch=synchronizer#2222222222222222222222222222222222222222\"",
        );
    assert_eq!(
        rendered.as_str(),
        expected,
        "the @generated header, entry order, and every untouched byte survive"
    );
    assert_eq!(
        lock.package_version(&DependencyName::new("signal-frame"))
            .map(|version| version.as_str()),
        Some("0.3.0"),
        "the read model stays coherent with the document"
    );
}

/// A lock recording the same package twice (two sources or deliberate old
/// revisions alongside current ones), plus one deliberately rev-pinned
/// entry — the sema-engine shape.
const ALIASED_LOCK_TEXT: &str = r#"# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "sema-engine"
version = "0.4.0"
source = "git+https://github.com/LiGoldragon/sema-engine.git?rev=3333333333333333333333333333333333333333#3333333333333333333333333333333333333333"

[[package]]
name = "signal-frame"
version = "0.2.0"
source = "git+https://github.com/LiGoldragon/signal-frame.git?branch=main#1111111111111111111111111111111111111111"

[[package]]
name = "signal-frame"
version = "0.1.0"
source = "git+https://github.com/LiGoldragon/signal-frame.git?rev=4444444444444444444444444444444444444444#4444444444444444444444444444444444444444"
"#;

/// Same-name lock entries must not alias to the first match: the repin
/// fails loud instead of rewriting whichever entry the iteration found.
#[test]
fn same_name_lock_entries_fail_loud_instead_of_aliasing() {
    let component = ComponentName::new("consumer");
    let mut lock = CargoLock::from_toml_text(ALIASED_LOCK_TEXT, &component).expect("lock decodes");
    let error = lock
        .repin_git_package(
            &DependencyName::new("signal-frame"),
            GitReference::Branch(BranchName::synchronizer()),
            CommitIdentifier::new("2222222222222222222222222222222222222222"),
            None,
        )
        .expect_err("aliased entries must not be repinned by first match");
    assert!(
        matches!(
            &error,
            Error::UnbumpablePin {
                reason: UnbumpablePinReason::MultipleEntries,
                ..
            }
        ),
        "unexpected error: {error}"
    );
    assert_eq!(
        lock.to_toml_text().as_str(),
        ALIASED_LOCK_TEXT,
        "the lock is left untouched"
    );
}

/// A `?rev=` source query is a deliberate pin: repinning it would override
/// the consumer's explicit choice, so the edit fails loud.
#[test]
fn deliberately_rev_pinned_lock_entries_fail_loud() {
    let component = ComponentName::new("consumer");
    let mut lock = CargoLock::from_toml_text(ALIASED_LOCK_TEXT, &component).expect("lock decodes");
    let error = lock
        .repin_git_package(
            &DependencyName::new("sema-engine"),
            GitReference::Branch(BranchName::synchronizer()),
            CommitIdentifier::new("2222222222222222222222222222222222222222"),
            None,
        )
        .expect_err("a rev-pinned entry must not be repinned");
    assert!(
        matches!(
            &error,
            Error::UnbumpablePin {
                reason: UnbumpablePinReason::DeliberateRevisionPin,
                ..
            }
        ),
        "unexpected error: {error}"
    );
}

#[test]
fn recorded_dependencies_feed_gap_detection() {
    let component = ComponentName::new("signal-router");
    let lock = CargoLock::from_toml_text(LOCK_TEXT, &component).expect("lock decodes");
    let recorded = lock
        .recorded_dependencies_of(&DependencyName::new("signal-router"))
        .expect("the consumer entry exists");
    let names: Vec<&str> = recorded.iter().map(|name| name.as_str()).collect();
    assert_eq!(names, vec!["serde", "signal-frame"]);
}
