//! Canonical TOML rendering.
//!
//! The pretty printer owns the workspace's TOML output policy: section
//! order, key alignment within a table, and Cargo's fixed lock header. It
//! renders from typed TOML values only; it never edits text it did not
//! produce.

use crate::error::Error;
use crate::types::TomlText;

/// A TOML rendering policy.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PrettyPrinter {
    style: Style,
}

impl PrettyPrinter {
    /// The workspace manifest style: aligned `=` within each dependency
    /// table, table order as authored.
    pub fn manifest_style() -> Self {
        Self {
            style: Style::Manifest,
        }
    }

    /// Cargo's own lock rendering, including the
    /// `# This file is automatically @generated by Cargo.` header.
    pub fn lock_style() -> Self {
        Self { style: Style::Lock }
    }

    /// Render a typed TOML value under this policy.
    pub fn render(&self, value: &toml::Value) -> Result<TomlText, Error> {
        todo!()
    }
}

/// The closed set of rendering policies.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Style {
    Manifest,
    Lock,
}
